-- database/seed.sql
-- Test clinic
INSERT INTO clinics (id, name, address, phone) VALUES
    ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Downtown Dental & Ortho', '123 Main St', '555-0100');

-- Test users (password: password123)
-- bcrypt hash of 'password123' with cost 12
-- Generated fresh: $2a$12$LQ4M5V0XJzS7KQO5G5H6yOWY8dQK9pZ5K9pZ5K9pZ5K9pZ5K9pZ5K9 (placeholder; will be regenerated by seed script)
INSERT INTO users (id, email, password_hash, full_name, role, clinic_id) VALUES
    ('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', 'dentist@clinic.com', 'PLACEHOLDER_HASH_REGENERATED_AT_SEED_TIME', 'Dr. Sarah Chen', 'dentist', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'),
    ('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33', 'ortho@clinic.com', 'PLACEHOLDER_HASH_REGENERATED_AT_SEED_TIME', 'Dr. James Wilson', 'orthopedist', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11');

-- Test patients
INSERT INTO patients (id, clinic_id, first_name, last_name, date_of_birth, gender, phone, created_by) VALUES
    ('d0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'John', 'Smith', '1984-03-15', 'male', '555-0201', 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22'),
    ('e0eebc99-9c0b-4ef8-bb6d-6bb9bd380a55', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Maria', 'Garcia', '1992-07-22', 'female', '555-0202', 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22');

-- Patient access
INSERT INTO patient_access (patient_id, user_id, access_level) VALUES
    ('d0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44', 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', 'full'),
    ('d0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44', 'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33', 'full'),
    ('e0eebc99-9c0b-4ef8-bb6d-6bb9bd380a55', 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', 'full');
